app = "crm-registration"
primary_region = "otp"

[build]
  builder = "paketobuildpacks/builder:base"

[http_service]
  internal_port = 8000  # Changed from 8080 to match your EXPOSE
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1